openapi: 3.0.3
info:
  title: XML OJP 2.0 API
  description: API that returns trip data in XML format.
  version: 0.0.1

servers:
  - url: https://api.example.com

paths:
  /ojp:
    post:
      summary: Main /ojp endpoint
      description: Main /ojp endpoint
      responses:
        "200":
          description: Successful response
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/OJP"
        "500":
          description: Server error

components:
  schemas:
    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__TripInfoParamStructure
    TripInfoParamStructure:
      type: object
      xml:
        name: TripInfoParam
      properties:
        includeCalls:
          type: boolean
          xml:
            name: IncludeCalls
        includeService:
          type: boolean
          xml:
            name: IncludeService
        includeTrackProjection:
          type: boolean
          xml:
            name: IncludeTrackProjection
        includePlacesContext:
          type: boolean
          xml:
            name: IncludePlacesContext
        includeSituationsContext:
          type: boolean
          xml:
            name: IncludeSituationsContext

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__OJPTripInfoRequestStructure
    OJPTripInfoRequest:
      type: object
      xml:
        name: OJPTripInfoRequest
      required:
        - requestTimestamp
        - journeyRef
        - operatingDayRef
      properties:
        requestTimestamp:
          type: string
          xml:
            name: RequestTimestamp
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        journeyRef:
          type: string
          xml:
            name: JourneyRef
        operatingDayRef:
          type: string
          xml:
            name: OperatingDayRef
        params:
          $ref: '#/components/schemas/TripInfoParamStructure'

    OJP:
      type: object
      xml:
        name: OJP
      required:
        - OJPRequest
      properties:
        OJPRequest:
          type: object
          xml:
            name: OJPRequest
          required:
            - serviceRequest
          properties:
            serviceRequest:
              type: object
              xml:
                name: ServiceRequest
                namespace: "http://www.siri.org.uk/siri"
                prefix: siri
              required:
                - requestTimestamp
                - requestorRef
                - OJPTripInfoRequest
              properties:
                serviceRequestContext:
                  $ref: './ojp-shared.yml#/components/schemas/ServiceRequestContext'
                  xml:
                    name: ServiceRequestContext
                requestTimestamp:
                  type: string
                  xml:
                    name: RequestTimestamp
                    namespace: "http://www.siri.org.uk/siri"
                    prefix: siri
                requestorRef:
                  type: string
                  xml:
                    name: RequestorRef
                    namespace: "http://www.siri.org.uk/siri"
                    prefix: siri
                OJPTripInfoRequest:
                  $ref: '#/components/schemas/OJPTripInfoRequest'
                  xml:
                    name: OJPTripInfoRequest              
        