openapi: 3.0.3
info:
  title: XML OJP 1.0 API
  description: API that returns trip data in XML format.
  version: 0.0.1

servers:
  - url: https://api.example.com

paths:
  /ojp:
    post:
      summary: Main /ojp endpoint
      description: Main /ojp endpoint
      responses:
        "200":
          description: Successful response
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/OJP"
        "500":
          description: Server error

components:
  schemas:
    # OJP 1.0 variation - <Location>
    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__PlaceResultStructure
    LocationResult:
      type: object
      xml:
        name: Location
      required:
        - location
        - complete
      properties:
        location:
          $ref: './ojp-shared.yml#/components/schemas/Location'
          xml:
            name: Location
        complete:
          type: boolean
          xml:
            name: Complete
        probability:
          type: number
          xml:
            name: Probability

    OJPLocationInformationDelivery:
      type: object
      xml:
        name: OJPLocationInformationDelivery
      required:
        - responseTimestamp
        - location
      properties:
        responseTimestamp:
          type: string
          xml:
            name: ResponseTimestamp
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        requestMessageRef:
          type: string
          xml:
            name: RequestMessageRef
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        defaultLanguage:
          type: string
          xml:
            name: DefaultLanguage
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        calcTime:
          type: string
          xml:
            name: CalcTime
        location:
          type: array
          xml:
            name: Location
          items:
            $ref: "#/components/schemas/LocationResult"

    OJP:
      type: object
      xml:
        name: OJP
      required:
        - OJPResponse
      properties:
        OJPResponse:
          type: object
          xml:
            name: OJPResponse
          required:
            - serviceDelivery
          properties:
            serviceDelivery:
              type: object
              xml:
                name: ServiceDelivery
                namespace: "http://www.siri.org.uk/siri"
                prefix: siri
              required:
                - responseTimestamp
                - producerRef
                - OJPLocationInformationDelivery
              properties:
                responseTimestamp:
                  type: string
                  xml:
                    name: ResponseTimestamp
                    namespace: "http://www.siri.org.uk/siri"
                    prefix: siri
                producerRef:
                  type: string
                  xml:
                    name: ProducerRef
                    namespace: "http://www.siri.org.uk/siri"
                    prefix: siri
                OJPLocationInformationDelivery:
                  $ref: '#/components/schemas/OJPLocationInformationDelivery'
                  xml:
                    name: OJPLocationInformationDelivery
    # OJP
        