openapi: 3.0.3
info:
  title: Empty API
  version: 1.0.0
paths: {}
components:
  schemas:
    # Variation of https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__GeneralAttributeStructure
    # OJP1.0 Text - OJP2.0 UserText
    GeneralAttribute:
      type: object
      xml:
        name: Attribute
      required:
        - text
        - code
      properties:
        text:
          $ref: '../../ojp-shared.yml#/components/schemas/InternationalText'
          xml:
            name: Text
        code:
          type: string
          xml:
            name: Code
        hireFacility:
          type: string
          xml:
            name: HireFacility
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        importance:
          type: number
          xml:
            name: Importance

    # modified from 'openapi/ojp-shared.yml#/components/schemas/DatedJourney'
    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__DatedJourneyStructure
    DatedJourney:
      type: object
      xml:
        name: Service
      required:
        - operatingDayRef
        - journeyRef
        - lineRef
        - mode
        - attribute
        - publishedLineName
      properties:
        conventionalModeOfOperation:
          type: string
          xml:
            name: ConventionalModeOfOperation
        operatingDayRef:
          type: string
          xml:
            name: OperatingDayRef
        journeyRef:
          type: string
          xml:
            name: JourneyRef
        publicCode:
          type: string
          xml:
            name: PublicCode
        lineRef:
          type: string
          xml:
            name: LineRef
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        directionRef:
          type: string
          xml:
            name: DirectionRef
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        mode:
          $ref: '../../ojp-shared.yml#/components/schemas/ModeStructure'
          xml:
            name: Mode
        productCategory:
          $ref: '../../ojp-shared.yml#/components/schemas/ProductCategory'
          xml:
            name: ProductCategory
        publishedLineName:
          $ref: '../../ojp-shared.yml#/components/schemas/InternationalText'
          xml:
            name: PublishedLineName
        trainNumber:
          type: string
          xml:
            name: TrainNumber
        attribute:
          type: array
          xml:
            name: Attribute
          items:
            $ref: '#/components/schemas/GeneralAttribute'
        operatorRef:
          type: string
          xml:
            name: OperatorRef
        destinationStopPointRef:
          type: string
          xml:
            name: DestinationStopPointRef
        destinationText:
          $ref: '../../ojp-shared.yml#/components/schemas/InternationalText'
          xml:
            name: 
        unplanned:
          type: boolean
          xml:
            name: Unplanned
        cancelled:
          type: boolean
          xml:
            name: Cancelled
        deviation:
          type: boolean
          xml:
            name: Deviation
    # DatedJourney

    # Variation of Place
    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__PlaceStructure
    Location:
      type: object
      xml:
        name: Location
      required:
        - locationName
        - geoPosition
        - mode
        - attribute
      properties:
        stopPoint:
          $ref: '../../ojp-shared.yml#/components/schemas/StopPoint'
          xml:
            name: StopPoint
        stopPlace:
          $ref: '../../ojp-shared.yml#/components/schemas/StopPlace'
          xml:
            name: StopPlace
        topographicPlace:
          $ref: '../../ojp-shared.yml#/components/schemas/TopographicPlace'
          xml:
            name: TopographicPlace
        pointOfInterest:
          $ref: '../../ojp-shared.yml#/components/schemas/PointOfInterest'
          xml:
            name: PointOfInterest
        address:
          $ref: '../../ojp-shared.yml#/components/schemas/Address'
          xml:
            name: Address
        locationName:
          $ref: '../../ojp-shared.yml#/components/schemas/InternationalText'
          xml:
            name: LocationName
        geoPosition:
          $ref: '../../ojp-shared.yml#/components/schemas/GeoPosition'
          xml:
            name: GeoPosition
        mode:
          type: array
          xml:
            name: Mode
          items:
            $ref: '../../ojp-shared.yml#/components/schemas/ModeStructure'
        attribute:
          type: array
          xml:
            name: Attribute
          items:
            $ref: '#/components/schemas/GeneralAttribute'
        extension:
          type: object
          xml:
            name: Extension
          properties:
            locationExtensionStructure:
              type: object
              xml:
                name: LocationExtensionStructure
              additionalProperties:
                type: string
